# Generated by Django 2.2.6 on 2019-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191215_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_to',
            field=models.URLField(max_length=250),
        ),
    ]
