# Generated by Django 2.2.6 on 2019-12-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xfzauth', '0002_auto_20191209_2150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
